-- /**************************************************************************************/
-- 创建数据库【清算外盘期货】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_clfofu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_clfofu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：清算外盘期货_结算_合约交割参数表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfost_deli_param;
CREATE TABLE tb_clfost_deli_param (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    exch_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    deli_price decimal(16,9) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfost_deli_param_1 on tb_clfost_deli_param (contrc_code_no);

-- 创建数据表：清算外盘期货_结算_组合占用保证金表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfost_posi_capture_margin;
CREATE TABLE tb_clfost_posi_capture_margin (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfost_posi_capture_margin_1 on tb_clfost_posi_capture_margin (init_date,asset_acco_no,futu_acco_no,comb_code);
create index idx_tb_clfost_posi_capture_margin_2 on tb_clfost_posi_capture_margin (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：历史_清算外盘期货_结算_组合占用保证金表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfost_posi_capture_margin_his;
CREATE TABLE tb_clfost_posi_capture_margin_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfost_posi_capture_margin_his_1 on tb_clfost_posi_capture_margin_his (init_date,asset_acco_no,futu_acco_no,comb_code);
create index idx_tb_clfost_posi_capture_margin_his_2 on tb_clfost_posi_capture_margin_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：清算外盘期货_结算_待入账记录表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfost_pre_entry;
CREATE TABLE tb_clfost_pre_entry (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    init_date int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    entry_status varchar(2) NOT NULL ,
    undo_status varchar(2) NOT NULL ,
    entry_money_jour_no bigint NOT NULL ,
    entry_posi_jour_no bigint NOT NULL ,
    deli_jour_no bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfost_pre_entry_1 on tb_clfost_pre_entry (pass_no,out_acco,exch_no,strike_date,strike_no);
create index idx_tb_clfost_pre_entry_2 on tb_clfost_pre_entry (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：历史_清算外盘期货_结算_待入账记录表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfost_pre_entry_his;
CREATE TABLE tb_clfost_pre_entry_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    init_date int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    entry_status varchar(2) NOT NULL ,
    undo_status varchar(2) NOT NULL ,
    entry_money_jour_no bigint NOT NULL ,
    entry_posi_jour_no bigint NOT NULL ,
    deli_jour_no bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfost_pre_entry_his_1 on tb_clfost_pre_entry_his (pass_no,out_acco,exch_no,strike_date,strike_no);
create index idx_tb_clfost_pre_entry_his_2 on tb_clfost_pre_entry_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：清算外盘期货_结算_入账异常表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfost_entry_error;
CREATE TABLE tb_clfost_entry_error (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    undo_error_no int NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfost_entry_error_1 on tb_clfost_entry_error (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：历史_清算外盘期货_结算_入账异常表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfost_entry_error_his;
CREATE TABLE tb_clfost_entry_error_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    undo_error_no int NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfost_entry_error_his_1 on tb_clfost_entry_error_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：清算外盘期货_结算_统计表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfost_total;
CREATE TABLE tb_clfost_total (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    busi_flag int NOT NULL ,
    sett_num int NOT NULL ,
    entry_qty decimal(18,2) NOT NULL ,
    entry_amt decimal(32,6) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfost_total_1 on tb_clfost_total (init_date,co_no,pd_no,exch_group_no,asset_acco_no,crncy_type,busi_flag);
create index idx_tb_clfost_total_2 on tb_clfost_total (init_date,exch_no,futu_acco_no,contrc_code_no,busi_flag);
commit;
