-- /**************************************************************************************/
-- 创建数据库【交易证券】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：交易证券_交易_订单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_order;
CREATE TABLE tb_tdsetd_order (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    stamp_tax decimal(18,4) NOT NULL ,
    trans_fee decimal(18,4) NOT NULL ,
    brkage_fee decimal(18,4) NOT NULL ,
    SEC_charges decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    trade_tax decimal(18,4) NOT NULL ,
    trade_cost_fee decimal(18,4) NOT NULL ,
    trade_system_use_fee decimal(18,4) NOT NULL ,
    stock_settle_fee decimal(18,4) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_bond_accr_intrst decimal(18,4) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    order_frozen_amt decimal(18,4) NOT NULL ,
    order_frozen_qty decimal(18,2) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    cost_calc_type int NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    record_valid_flag int NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    combo_posi_id bigint NOT NULL ,
    strategy_id bigint NOT NULL ,
    sett_flag int NOT NULL ,
    target_stock_code varchar(6) NOT NULL ,
    target_stock_code_no int NOT NULL ,
    registration_agency varchar(32) NOT NULL ,
    trade_acco varchar(32) NOT NULL ,
    contra_no varchar(32) NOT NULL ,
    asset_acco_type int NOT NULL ,
    exist_debt_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_order_1 on tb_tdsetd_order (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdsetd_order_2 on tb_tdsetd_order (order_date,order_batch_no);
create index idx_tb_tdsetd_order_3 on tb_tdsetd_order (order_date,order_status);
create index idx_tb_tdsetd_order_4 on tb_tdsetd_order (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_order_5 on tb_tdsetd_order (stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_order_6 on tb_tdsetd_order (exter_comm_flag,record_valid_flag);
create index idx_tb_tdsetd_order_7 on tb_tdsetd_order (co_no,pd_no,exch_group_no,order_status);
create index idx_tb_tdsetd_order_8 on tb_tdsetd_order (update_date,update_time);
create index idx_tb_tdsetd_order_9 on tb_tdsetd_order (co_no,comm_id,strategy_id);

-- 创建数据表：历史_交易证券_交易_订单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_order_his;
CREATE TABLE tb_tdsetd_order_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    stamp_tax decimal(18,4) NOT NULL ,
    trans_fee decimal(18,4) NOT NULL ,
    brkage_fee decimal(18,4) NOT NULL ,
    SEC_charges decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    trade_tax decimal(18,4) NOT NULL ,
    trade_cost_fee decimal(18,4) NOT NULL ,
    trade_system_use_fee decimal(18,4) NOT NULL ,
    stock_settle_fee decimal(18,4) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_bond_accr_intrst decimal(18,4) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    order_frozen_amt decimal(18,4) NOT NULL ,
    order_frozen_qty decimal(18,2) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    cost_calc_type int NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    record_valid_flag int NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    combo_posi_id bigint NOT NULL ,
    strategy_id bigint NOT NULL ,
    sett_flag int NOT NULL ,
    target_stock_code varchar(6) NOT NULL ,
    target_stock_code_no int NOT NULL ,
    registration_agency varchar(32) NOT NULL ,
    trade_acco varchar(32) NOT NULL ,
    contra_no varchar(32) NOT NULL ,
    asset_acco_type int NOT NULL ,
    exist_debt_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_order_his_1 on tb_tdsetd_order_his (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdsetd_order_his_2 on tb_tdsetd_order_his (order_date,order_batch_no);
create index idx_tb_tdsetd_order_his_3 on tb_tdsetd_order_his (order_date,order_status);
create index idx_tb_tdsetd_order_his_4 on tb_tdsetd_order_his (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_order_his_5 on tb_tdsetd_order_his (stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_order_his_6 on tb_tdsetd_order_his (exter_comm_flag,record_valid_flag);
create index idx_tb_tdsetd_order_his_7 on tb_tdsetd_order_his (co_no,pd_no,exch_group_no,order_status);
create index idx_tb_tdsetd_order_his_8 on tb_tdsetd_order_his (update_date,update_time);
create index idx_tb_tdsetd_order_his_9 on tb_tdsetd_order_his (co_no,comm_id,strategy_id);

-- 创建数据表：交易证券_交易_通道订单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_channelorder;
CREATE TABLE tb_tdsetd_channelorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_channelorder_1 on tb_tdsetd_channelorder (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdsetd_channelorder_2 on tb_tdsetd_channelorder (order_date,order_batch_no);
create index idx_tb_tdsetd_channelorder_3 on tb_tdsetd_channelorder (order_date,order_status);
create index idx_tb_tdsetd_channelorder_4 on tb_tdsetd_channelorder (init_date,co_no,pd_no,exch_group_no);

-- 创建数据表：历史_交易证券_交易_通道订单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_channelorder_his;
CREATE TABLE tb_tdsetd_channelorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_channelorder_his_1 on tb_tdsetd_channelorder_his (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdsetd_channelorder_his_2 on tb_tdsetd_channelorder_his (order_date,order_batch_no);
create index idx_tb_tdsetd_channelorder_his_3 on tb_tdsetd_channelorder_his (order_date,order_status);
create index idx_tb_tdsetd_channelorder_his_4 on tb_tdsetd_channelorder_his (init_date,co_no,pd_no,exch_group_no);

-- 创建数据表：交易证券_交易_新股申购表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_purchaseorder;
CREATE TABLE tb_tdsetd_purchaseorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_id bigint NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    order_frozen_amt decimal(18,4) NOT NULL ,
    nav_asset decimal(18,4) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    sett_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_purchaseorder_1 on tb_tdsetd_purchaseorder (stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_purchaseorder_2 on tb_tdsetd_purchaseorder (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdsetd_purchaseorder_3 on tb_tdsetd_purchaseorder (sett_flag);
create index idx_tb_tdsetd_purchaseorder_4 on tb_tdsetd_purchaseorder (order_date);

-- 创建数据表：历史_交易证券_交易_新股申购表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_purchaseorder_his;
CREATE TABLE tb_tdsetd_purchaseorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_id bigint NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    order_frozen_amt decimal(18,4) NOT NULL ,
    nav_asset decimal(18,4) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    sett_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_purchaseorder_his_1 on tb_tdsetd_purchaseorder_his (stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_purchaseorder_his_2 on tb_tdsetd_purchaseorder_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdsetd_purchaseorder_his_3 on tb_tdsetd_purchaseorder_his (sett_flag);
create index idx_tb_tdsetd_purchaseorder_his_4 on tb_tdsetd_purchaseorder_his (order_date);

-- 创建数据表：交易证券_交易_撤单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_cancel;
CREATE TABLE tb_tdsetd_cancel (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    external_no bigint NOT NULL ,
    wtdraw_batch_no int NOT NULL ,
    wtdraw_date int NOT NULL ,
    wtdraw_time int NOT NULL ,
    order_date int NOT NULL ,
    order_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    wtdraw_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    wtdraw_remark varchar(255) NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    trade_acco varchar(32) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_cancel_1 on tb_tdsetd_cancel (order_id);
create index idx_tb_tdsetd_cancel_2 on tb_tdsetd_cancel (report_date,report_no);
create index idx_tb_tdsetd_cancel_3 on tb_tdsetd_cancel (wtdraw_status);
create index idx_tb_tdsetd_cancel_4 on tb_tdsetd_cancel (wtdraw_date);

-- 创建数据表：历史_交易证券_交易_撤单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_cancel_his;
CREATE TABLE tb_tdsetd_cancel_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    external_no bigint NOT NULL ,
    wtdraw_batch_no int NOT NULL ,
    wtdraw_date int NOT NULL ,
    wtdraw_time int NOT NULL ,
    order_date int NOT NULL ,
    order_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    wtdraw_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    wtdraw_remark varchar(255) NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    trade_acco varchar(32) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_cancel_his_1 on tb_tdsetd_cancel_his (order_id);
create index idx_tb_tdsetd_cancel_his_2 on tb_tdsetd_cancel_his (report_date,report_no);
create index idx_tb_tdsetd_cancel_his_3 on tb_tdsetd_cancel_his (wtdraw_status);
create index idx_tb_tdsetd_cancel_his_4 on tb_tdsetd_cancel_his (wtdraw_date);

-- 创建数据表：交易证券_交易_预埋订单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_preorder;
CREATE TABLE tb_tdsetd_preorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    pre_order_date int NOT NULL ,
    pre_order_time int NOT NULL ,
    pre_order_dir int NOT NULL ,
    pre_order_type int NOT NULL ,
    pre_order_price decimal(16,9) NOT NULL ,
    pre_order_qty decimal(18,2) NOT NULL ,
    pre_order_status varchar(2) NOT NULL ,
    pre_price_type int NOT NULL ,
    price_offset decimal(16,9) NOT NULL ,
    pre_begin_date int NOT NULL ,
    pre_end_date int NOT NULL ,
    pre_begin_time int NOT NULL ,
    pre_end_time int NOT NULL ,
    trig_type int NOT NULL ,
    trig_price decimal(16,9) NOT NULL ,
    trig_date int NOT NULL ,
    trig_time int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_id bigint NOT NULL ,
    is_trace int NOT NULL ,
    price_up decimal(16,9) NOT NULL ,
    order_no_str varchar(2048) NOT NULL ,
    keep_trace int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_preorder_1 on tb_tdsetd_preorder (order_date,asset_acco_no,stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_preorder_2 on tb_tdsetd_preorder (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_preorder_3 on tb_tdsetd_preorder (pre_order_type);
create index idx_tb_tdsetd_preorder_4 on tb_tdsetd_preorder (pre_order_status);

-- 创建数据表：历史_交易证券_交易_预埋订单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_preorder_his;
CREATE TABLE tb_tdsetd_preorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    pre_order_date int NOT NULL ,
    pre_order_time int NOT NULL ,
    pre_order_dir int NOT NULL ,
    pre_order_type int NOT NULL ,
    pre_order_price decimal(16,9) NOT NULL ,
    pre_order_qty decimal(18,2) NOT NULL ,
    pre_order_status varchar(2) NOT NULL ,
    pre_price_type int NOT NULL ,
    price_offset decimal(16,9) NOT NULL ,
    pre_begin_date int NOT NULL ,
    pre_end_date int NOT NULL ,
    pre_begin_time int NOT NULL ,
    pre_end_time int NOT NULL ,
    trig_type int NOT NULL ,
    trig_price decimal(16,9) NOT NULL ,
    trig_date int NOT NULL ,
    trig_time int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_id bigint NOT NULL ,
    is_trace int NOT NULL ,
    price_up decimal(16,9) NOT NULL ,
    order_no_str varchar(2048) NOT NULL ,
    keep_trace int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_preorder_his_1 on tb_tdsetd_preorder_his (order_date,asset_acco_no,stock_acco_no,stock_code_no);
create index idx_tb_tdsetd_preorder_his_2 on tb_tdsetd_preorder_his (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_preorder_his_3 on tb_tdsetd_preorder_his (pre_order_type);
create index idx_tb_tdsetd_preorder_his_4 on tb_tdsetd_preorder_his (pre_order_status);

-- 创建数据表：交易证券_交易_篮子订单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_basketorder;
CREATE TABLE tb_tdsetd_basketorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    basket_id bigint NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    basket_trade_type int NOT NULL ,
    basket_trade_amt decimal(18,4) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_basketorder_1 on tb_tdsetd_basketorder (order_date,opor_no,order_batch_no);

-- 创建数据表：历史_交易证券_交易_篮子订单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_basketorder_his;
CREATE TABLE tb_tdsetd_basketorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    basket_id bigint NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    basket_trade_type int NOT NULL ,
    basket_trade_amt decimal(18,4) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_basketorder_his_1 on tb_tdsetd_basketorder_his (order_date,opor_no,order_batch_no);

-- 创建数据表：交易证券_交易_改单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_modifyorder;
CREATE TABLE tb_tdsetd_modifyorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    modi_order_date int NOT NULL ,
    modi_order_time int NOT NULL ,
    modi_batch_no int NOT NULL ,
    order_id bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_dir int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    price_type int NOT NULL ,
    modi_order_price decimal(16,9) NOT NULL ,
    modi_order_qty decimal(18,2) NOT NULL ,
    modi_order_status varchar(2) NOT NULL ,
    modi_price_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    new_order_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_modifyorder_1 on tb_tdsetd_modifyorder (modi_order_date,order_id);
create index idx_tb_tdsetd_modifyorder_2 on tb_tdsetd_modifyorder (init_date,co_no,pd_no,exch_group_no);

-- 创建数据表：历史_交易证券_交易_改单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_modifyorder_his;
CREATE TABLE tb_tdsetd_modifyorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    modi_order_date int NOT NULL ,
    modi_order_time int NOT NULL ,
    modi_batch_no int NOT NULL ,
    order_id bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_dir int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    price_type int NOT NULL ,
    modi_order_price decimal(16,9) NOT NULL ,
    modi_order_qty decimal(18,2) NOT NULL ,
    modi_order_status varchar(2) NOT NULL ,
    modi_price_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    new_order_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_modifyorder_his_1 on tb_tdsetd_modifyorder_his (modi_order_date,order_id);
create index idx_tb_tdsetd_modifyorder_his_2 on tb_tdsetd_modifyorder_his (init_date,co_no,pd_no,exch_group_no);

-- 创建数据表：交易证券_交易_订单汇总表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_sumorder;
CREATE TABLE tb_tdsetd_sumorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    external_no bigint NOT NULL ,
    order_date int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_sum_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    waste_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    stamp_tax decimal(18,4) NOT NULL ,
    trans_fee decimal(18,4) NOT NULL ,
    brkage_fee decimal(18,4) NOT NULL ,
    SEC_charges decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    trade_tax decimal(18,4) NOT NULL ,
    trade_cost_fee decimal(18,4) NOT NULL ,
    trade_system_use_fee decimal(18,4) NOT NULL ,
    stock_settle_fee decimal(18,4) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    strike_bond_accr_intrst decimal(18,4) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    record_valid_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_sumorder_1 on tb_tdsetd_sumorder (order_date,co_no,order_batch_no);
create index idx_tb_tdsetd_sumorder_2 on tb_tdsetd_sumorder (opor_no,order_oper_way);
create index idx_tb_tdsetd_sumorder_3 on tb_tdsetd_sumorder (exter_comm_flag,record_valid_flag);

-- 创建数据表：历史_交易证券_交易_订单汇总表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_sumorder_his;
CREATE TABLE tb_tdsetd_sumorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    external_no bigint NOT NULL ,
    order_date int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_sum_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    waste_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    all_fee decimal(18,4) NOT NULL ,
    stamp_tax decimal(18,4) NOT NULL ,
    trans_fee decimal(18,4) NOT NULL ,
    brkage_fee decimal(18,4) NOT NULL ,
    SEC_charges decimal(18,4) NOT NULL ,
    other_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    trade_tax decimal(18,4) NOT NULL ,
    trade_cost_fee decimal(18,4) NOT NULL ,
    trade_system_use_fee decimal(18,4) NOT NULL ,
    stock_settle_fee decimal(18,4) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    strike_bond_accr_intrst decimal(18,4) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    record_valid_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_sumorder_his_1 on tb_tdsetd_sumorder_his (order_date,co_no,order_batch_no);
create index idx_tb_tdsetd_sumorder_his_2 on tb_tdsetd_sumorder_his (opor_no,order_oper_way);
create index idx_tb_tdsetd_sumorder_his_3 on tb_tdsetd_sumorder_his (exter_comm_flag,record_valid_flag);

-- 创建数据表：交易证券_交易_待执行订单表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_pendorder;
CREATE TABLE tb_tdsetd_pendorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    exec_price_type int NOT NULL ,
    price_offset decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    external_no bigint NOT NULL ,
    pend_order_status varchar(2) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_pendorder_1 on tb_tdsetd_pendorder (order_date,order_batch_no);
create index idx_tb_tdsetd_pendorder_2 on tb_tdsetd_pendorder (comm_batch_no,comm_id);
create index idx_tb_tdsetd_pendorder_3 on tb_tdsetd_pendorder (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_pendorder_4 on tb_tdsetd_pendorder (stock_code_no);

-- 创建数据表：历史_交易证券_交易_待执行订单表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_pendorder_his;
CREATE TABLE tb_tdsetd_pendorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    trade_code_no int NOT NULL ,
    target_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    price_type int NOT NULL ,
    exec_price_type int NOT NULL ,
    price_offset decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    intrst_days int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    external_no bigint NOT NULL ,
    pend_order_status varchar(2) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_pendorder_his_1 on tb_tdsetd_pendorder_his (order_date,order_batch_no);
create index idx_tb_tdsetd_pendorder_his_2 on tb_tdsetd_pendorder_his (comm_batch_no,comm_id);
create index idx_tb_tdsetd_pendorder_his_3 on tb_tdsetd_pendorder_his (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdsetd_pendorder_his_4 on tb_tdsetd_pendorder_his (stock_code_no);

-- 创建数据表：交易证券_交易_组合交易流水记录表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_combotradelog;
CREATE TABLE tb_tdsetd_combotradelog (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    opor_no int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    combo_copies decimal(18,2) NOT NULL ,
    combo_date int NOT NULL ,
    combo_time int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_combotradelog_1 on tb_tdsetd_combotradelog (order_batch_no,combo_code);
create index idx_tb_tdsetd_combotradelog_2 on tb_tdsetd_combotradelog (combo_date);

-- 创建数据表：历史_交易证券_交易_组合交易流水记录表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsetd_combotradelog_his;
CREATE TABLE tb_tdsetd_combotradelog_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    opor_no int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    combo_copies decimal(18,2) NOT NULL ,
    combo_date int NOT NULL ,
    combo_time int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsetd_combotradelog_his_1 on tb_tdsetd_combotradelog_his (order_batch_no,combo_code);
create index idx_tb_tdsetd_combotradelog_his_2 on tb_tdsetd_combotradelog_his (combo_date);

-- 创建数据表：交易证券_交易_交易时间配置表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsetd_trdtimeconfig;
CREATE TABLE tb_tdsetd_trdtimeconfig (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    co_no int NOT NULL ,
    exch_no int NOT NULL ,
    am_trd_begin_time int NOT NULL ,
    am_trd_end_time int NOT NULL ,
    pm_trd_begin_time int NOT NULL ,
    pm_trd_end_time int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsetd_trdtimeconfig_1 on tb_tdsetd_trdtimeconfig (co_no,exch_no);
commit;
