-- /**************************************************************************************/
-- 创建数据库【交易证券】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：交易证券_交易运维_指令汇总考核表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsebk_sumcommand_check;
CREATE TABLE tb_tdsebk_sumcommand_check (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    comm_await_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_sum_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    max_comm_comple_date int NOT NULL ,
    max_comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_qty decimal(18,2) NOT NULL ,
    comm_sum_approve_status varchar(2) NOT NULL ,
    basket_id bigint NOT NULL ,
    buy_order_qty decimal(18,2) NOT NULL ,
    sell_order_qty decimal(18,2) NOT NULL ,
    buy_comm_qty decimal(18,2) NOT NULL ,
    sell_comm_qty decimal(18,2) NOT NULL ,
    buy_strike_qty decimal(18,2) NOT NULL ,
    sell_strike_qty decimal(18,2) NOT NULL ,
    buy_strike_amt decimal(18,4) NOT NULL ,
    sell_strike_amt decimal(18,4) NOT NULL ,
    buy_comm_amt decimal(18,4) NOT NULL ,
    sell_comm_amt decimal(18,4) NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    valid_aver_price decimal(16,9) NOT NULL ,
    valid_aver_price_allday decimal(16,9) NOT NULL ,
    exec_price_diff decimal(18,12) NOT NULL ,
    exec_price_diff_allday decimal(18,12) NOT NULL ,
    valid_ratio decimal(18,12) NOT NULL ,
    valid_ratio_allday decimal(18,12) NOT NULL ,
    valid_qty decimal(18,2) NOT NULL ,
    valid_qty_allday decimal(18,2) NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsebk_sumcommand_check_1 on tb_tdsebk_sumcommand_check (comm_date,co_no,comm_batch_no,comm_executor);
create index idx_tb_tdsebk_sumcommand_check_2 on tb_tdsebk_sumcommand_check (opor_no,comm_oper_way);
create index idx_tb_tdsebk_sumcommand_check_3 on tb_tdsebk_sumcommand_check (exter_comm_flag);

-- 创建数据表：历史_交易证券_交易运维_指令汇总考核表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsebk_sumcommand_check_his;
CREATE TABLE tb_tdsebk_sumcommand_check_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    comm_await_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_sum_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    max_comm_comple_date int NOT NULL ,
    max_comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_qty decimal(18,2) NOT NULL ,
    comm_sum_approve_status varchar(2) NOT NULL ,
    basket_id bigint NOT NULL ,
    buy_order_qty decimal(18,2) NOT NULL ,
    sell_order_qty decimal(18,2) NOT NULL ,
    buy_comm_qty decimal(18,2) NOT NULL ,
    sell_comm_qty decimal(18,2) NOT NULL ,
    buy_strike_qty decimal(18,2) NOT NULL ,
    sell_strike_qty decimal(18,2) NOT NULL ,
    buy_strike_amt decimal(18,4) NOT NULL ,
    sell_strike_amt decimal(18,4) NOT NULL ,
    buy_comm_amt decimal(18,4) NOT NULL ,
    sell_comm_amt decimal(18,4) NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    valid_aver_price decimal(16,9) NOT NULL ,
    valid_aver_price_allday decimal(16,9) NOT NULL ,
    exec_price_diff decimal(18,12) NOT NULL ,
    exec_price_diff_allday decimal(18,12) NOT NULL ,
    valid_ratio decimal(18,12) NOT NULL ,
    valid_ratio_allday decimal(18,12) NOT NULL ,
    valid_qty decimal(18,2) NOT NULL ,
    valid_qty_allday decimal(18,2) NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsebk_sumcommand_check_his_1 on tb_tdsebk_sumcommand_check_his (comm_date,co_no,comm_batch_no,comm_executor);
create index idx_tb_tdsebk_sumcommand_check_his_2 on tb_tdsebk_sumcommand_check_his (opor_no,comm_oper_way);
create index idx_tb_tdsebk_sumcommand_check_his_3 on tb_tdsebk_sumcommand_check_his (exter_comm_flag);

-- 创建数据表：交易证券_交易运维_场外基金成交回报表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsebk_off_site_fundrsp;
CREATE TABLE tb_tdsebk_off_site_fundrsp (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    report_date int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(64) NOT NULL ,
    order_dir int NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_deal_type int NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsebk_off_site_fundrsp_1 on tb_tdsebk_off_site_fundrsp (strike_date,strike_no,exch_no);
create index idx_tb_tdsebk_off_site_fundrsp_2 on tb_tdsebk_off_site_fundrsp (init_date);

-- 创建数据表：历史_交易证券_交易运维_场外基金成交回报表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsebk_off_site_fundrsp_his;
CREATE TABLE tb_tdsebk_off_site_fundrsp_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    report_date int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(64) NOT NULL ,
    order_dir int NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_deal_type int NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsebk_off_site_fundrsp_his_1 on tb_tdsebk_off_site_fundrsp_his (strike_date,strike_no,exch_no);
create index idx_tb_tdsebk_off_site_fundrsp_his_2 on tb_tdsebk_off_site_fundrsp_his (init_date);

-- 创建数据表：交易证券_交易运维_结算资金股份流水表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsebk_setfushflow;
CREATE TABLE tb_tdsebk_setfushflow (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    strike_no varchar(64) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsebk_setfushflow_1 on tb_tdsebk_setfushflow (out_acco);
create index idx_tb_tdsebk_setfushflow_2 on tb_tdsebk_setfushflow (report_no,strike_no);
commit;
