-- /**************************************************************************************/
-- 创建数据库【交易证券】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：交易证券_策略_策略插件状态表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsest_strategypluginstatus;
CREATE TABLE tb_tdsest_strategypluginstatus (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    strategy_plugin_status varchar(2) NOT NULL ,
    strategy_plugin_type int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsest_strategypluginstatus_1 on tb_tdsest_strategypluginstatus (strategy_plugin_type);
create index idx_tb_tdsest_strategypluginstatus_2 on tb_tdsest_strategypluginstatus (strategy_plugin_status);

-- 创建数据表：交易证券_策略_策略表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsest_strategyorder;
CREATE TABLE tb_tdsest_strategyorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    strategy_batch_no int NOT NULL ,
    orig_strategy_id bigint NOT NULL ,
    strategy_exec_broker varchar(16) NOT NULL ,
    strategy_exec_kind int NOT NULL ,
    strategy_exec_comm_str varchar(2048) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    strategy_amt decimal(18,4) NOT NULL ,
    strategy_valid_type int NOT NULL ,
    strategy_rule_way varchar(4) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    strategy_date int NOT NULL ,
    strategy_time int NOT NULL ,
    margin_trade_type int NOT NULL ,
    target_strategy_type varchar(16) NOT NULL ,
    target_strategy_param varchar(2048) NOT NULL ,
    strategy_contr_comm varchar(2048) NOT NULL ,
    strategy_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    valid_order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    valid_wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    strategy_price_type int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_id bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsest_strategyorder_1 on tb_tdsest_strategyorder (exch_group_no,order_batch_no);
create index idx_tb_tdsest_strategyorder_2 on tb_tdsest_strategyorder (stock_code_no);
create index idx_tb_tdsest_strategyorder_3 on tb_tdsest_strategyorder (strategy_date);
create index idx_tb_tdsest_strategyorder_4 on tb_tdsest_strategyorder (comm_batch_no);
create index idx_tb_tdsest_strategyorder_5 on tb_tdsest_strategyorder (co_no,comm_id,strategy_status,orig_strategy_id);

-- 创建数据表：历史_交易证券_策略_策略表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsest_strategyorder_his;
CREATE TABLE tb_tdsest_strategyorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    strategy_batch_no int NOT NULL ,
    orig_strategy_id bigint NOT NULL ,
    strategy_exec_broker varchar(16) NOT NULL ,
    strategy_exec_kind int NOT NULL ,
    strategy_exec_comm_str varchar(2048) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    strategy_amt decimal(18,4) NOT NULL ,
    strategy_valid_type int NOT NULL ,
    strategy_rule_way varchar(4) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    strategy_date int NOT NULL ,
    strategy_time int NOT NULL ,
    margin_trade_type int NOT NULL ,
    target_strategy_type varchar(16) NOT NULL ,
    target_strategy_param varchar(2048) NOT NULL ,
    strategy_contr_comm varchar(2048) NOT NULL ,
    strategy_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    valid_order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    valid_wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    strategy_price_type int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_id bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsest_strategyorder_his_1 on tb_tdsest_strategyorder_his (exch_group_no,order_batch_no);
create index idx_tb_tdsest_strategyorder_his_2 on tb_tdsest_strategyorder_his (stock_code_no);
create index idx_tb_tdsest_strategyorder_his_3 on tb_tdsest_strategyorder_his (strategy_date);
create index idx_tb_tdsest_strategyorder_his_4 on tb_tdsest_strategyorder_his (comm_batch_no);
create index idx_tb_tdsest_strategyorder_his_5 on tb_tdsest_strategyorder_his (co_no,comm_id,strategy_status,orig_strategy_id);

-- 创建数据表：交易证券_策略_策略流水表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsest_strategyorder_jour;
CREATE TABLE tb_tdsest_strategyorder_jour (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    strategy_batch_no int NOT NULL ,
    strategy_id bigint NOT NULL ,
    orig_strategy_id bigint NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    strategy_date int NOT NULL ,
    strategy_time int NOT NULL ,
    strategy_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_id bigint NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_id bigint NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    order_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    comm_batch_no int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsest_strategyorder_jour_1 on tb_tdsest_strategyorder_jour (exch_group_no,order_batch_no);
create index idx_tb_tdsest_strategyorder_jour_2 on tb_tdsest_strategyorder_jour (stock_code_no);
create index idx_tb_tdsest_strategyorder_jour_3 on tb_tdsest_strategyorder_jour (strategy_date);
create index idx_tb_tdsest_strategyorder_jour_4 on tb_tdsest_strategyorder_jour (comm_batch_no);

-- 创建数据表：历史_交易证券_策略_策略流水表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsest_strategyorder_jour_his;
CREATE TABLE tb_tdsest_strategyorder_jour_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    strategy_batch_no int NOT NULL ,
    strategy_id bigint NOT NULL ,
    orig_strategy_id bigint NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_acco varchar(16) NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    strategy_date int NOT NULL ,
    strategy_time int NOT NULL ,
    strategy_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_id bigint NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_id bigint NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    order_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    comm_batch_no int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdsest_strategyorder_jour_his_1 on tb_tdsest_strategyorder_jour_his (exch_group_no,order_batch_no);
create index idx_tb_tdsest_strategyorder_jour_his_2 on tb_tdsest_strategyorder_jour_his (stock_code_no);
create index idx_tb_tdsest_strategyorder_jour_his_3 on tb_tdsest_strategyorder_jour_his (strategy_date);
create index idx_tb_tdsest_strategyorder_jour_his_4 on tb_tdsest_strategyorder_jour_his (comm_batch_no);

-- 创建数据表：交易证券_策略_策略汇总表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdsest_strategyordersum;
CREATE TABLE tb_tdsest_strategyordersum (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    strategy_batch_no int NOT NULL ,
    strategy_exec_broker varchar(16) NOT NULL ,
    strategy_exec_kind int NOT NULL ,
    strategy_exec_comm_str varchar(2048) NOT NULL ,
    exch_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    strategy_amt decimal(18,4) NOT NULL ,
    strategy_valid_type int NOT NULL ,
    strategy_rule_way varchar(4) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    strategy_date int NOT NULL ,
    margin_trade_type int NOT NULL ,
    target_strategy_type varchar(16) NOT NULL ,
    target_strategy_param varchar(2048) NOT NULL ,
    strategy_contr_comm varchar(2048) NOT NULL ,
    strategy_sum_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    valid_order_qty decimal(18,2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    valid_wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    cancel_qty decimal(18,2) NOT NULL ,
    faild_qty decimal(18,2) NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    comm_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsest_strategyordersum_1 on tb_tdsest_strategyordersum (strategy_batch_no,strategy_date,co_no);
create index idx_tb_tdsest_strategyordersum_2 on tb_tdsest_strategyordersum (stock_code_no);
create index idx_tb_tdsest_strategyordersum_3 on tb_tdsest_strategyordersum (strategy_date);
create index idx_tb_tdsest_strategyordersum_4 on tb_tdsest_strategyordersum (exch_group_no,order_batch_no);

-- 创建数据表：历史_交易证券_策略_策略汇总表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdsest_strategyordersum_his;
CREATE TABLE tb_tdsest_strategyordersum_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    comm_opor int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    strategy_batch_no int NOT NULL ,
    strategy_exec_broker varchar(16) NOT NULL ,
    strategy_exec_kind int NOT NULL ,
    strategy_exec_comm_str varchar(2048) NOT NULL ,
    exch_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    stock_code_no int NOT NULL ,
    strategy_dir int NOT NULL ,
    strategy_qty decimal(18,2) NOT NULL ,
    cash_strategy_qty decimal(18,2) NOT NULL ,
    strategy_price decimal(16,9) NOT NULL ,
    price_type int NOT NULL ,
    strategy_amt decimal(18,4) NOT NULL ,
    strategy_valid_type int NOT NULL ,
    strategy_rule_way varchar(4) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    strategy_date int NOT NULL ,
    margin_trade_type int NOT NULL ,
    target_strategy_type varchar(16) NOT NULL ,
    target_strategy_param varchar(2048) NOT NULL ,
    strategy_contr_comm varchar(2048) NOT NULL ,
    strategy_sum_status varchar(2) NOT NULL ,
    strategy_deal_status varchar(2) NOT NULL ,
    strategy_deal_kind int NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_amt decimal(18,4) NOT NULL ,
    valid_order_qty decimal(18,2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    valid_wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    cancel_qty decimal(18,2) NOT NULL ,
    faild_qty decimal(18,2) NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    comm_batch_no int NOT NULL ,
    strategy_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdsest_strategyordersum_his_1 on tb_tdsest_strategyordersum_his (strategy_batch_no,strategy_date,co_no);
create index idx_tb_tdsest_strategyordersum_his_2 on tb_tdsest_strategyordersum_his (stock_code_no);
create index idx_tb_tdsest_strategyordersum_his_3 on tb_tdsest_strategyordersum_his (strategy_date);
create index idx_tb_tdsest_strategyordersum_his_4 on tb_tdsest_strategyordersum_his (exch_group_no,order_batch_no);
commit;
