-- /**************************************************************************************/
-- 创建数据库【清算外盘期货】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_clfofu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_clfofu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：清算外盘期货_清算_平仓明细表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_close_detail;
CREATE TABLE tb_clfocl_close_detail (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    strike_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    order_dir int NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    avail_closed_posi_qty decimal(18,2) NOT NULL ,
    today_posi_flag int NOT NULL ,
    link_row_id bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_close_detail_1 on tb_clfocl_close_detail (strike_date,asset_acco_no,futu_acco_no,contrc_code_no,order_dir,link_row_id);
create index idx_tb_clfocl_close_detail_2 on tb_clfocl_close_detail (link_row_id);

-- 创建数据表：清算外盘期货_清算_成交表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_out_busi;
CREATE TABLE tb_clfocl_out_busi (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_dir int NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    match_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_out_busi_1 on tb_clfocl_out_busi (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);

-- 创建数据表：历史_清算外盘期货_清算_成交表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_out_busi_his;
CREATE TABLE tb_clfocl_out_busi_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_dir int NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    match_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_out_busi_his_1 on tb_clfocl_out_busi_his (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);

-- 创建数据表：清算外盘期货_清算_订单表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_order;
CREATE TABLE tb_clfocl_order (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    comm_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_order_1 on tb_clfocl_order (asset_acco_no,order_date,order_no);

-- 创建数据表：历史_清算外盘期货_清算_订单表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_order_his;
CREATE TABLE tb_clfocl_order_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    comm_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_batch_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_order_his_1 on tb_clfocl_order_his (asset_acco_no,order_date,order_no);

-- 创建数据表：清算外盘期货_清算_成交配对表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_match;
CREATE TABLE tb_clfocl_match (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    clear_entry_type int NOT NULL ,
    match_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_match_1 on tb_clfocl_match (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);

-- 创建数据表：历史_清算外盘期货_清算_成交配对表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_match_his;
CREATE TABLE tb_clfocl_match_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    clear_entry_type int NOT NULL ,
    match_status varchar(2) NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_match_his_1 on tb_clfocl_match_his (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);

-- 创建数据表：清算外盘期货_清算_合并清算表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_merge_clear;
CREATE TABLE tb_clfocl_merge_clear (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    split_rece_margin decimal(32,6) NOT NULL ,
    split_strike_qty decimal(18,2) NOT NULL ,
    split_strike_amt decimal(32,6) NOT NULL ,
    split_report_fee decimal(32,6) NOT NULL ,
    split_cancel_fee decimal(32,6) NOT NULL ,
    split_deli_fee decimal(32,6) NOT NULL ,
    split_other_fee decimal(32,6) NOT NULL ,
    split_brkage_commis decimal(32,6) NOT NULL ,
    split_other_commis decimal(32,6) NOT NULL ,
    split_out_strike_qty decimal(18,2) NOT NULL ,
    split_out_strike_amt decimal(32,6) NOT NULL ,
    split_out_report_fee decimal(32,6) NOT NULL ,
    split_out_cancel_fee decimal(32,6) NOT NULL ,
    split_out_deli_fee decimal(32,6) NOT NULL ,
    split_out_other_fee decimal(32,6) NOT NULL ,
    split_out_brkage_commis decimal(32,6) NOT NULL ,
    split_out_other_commis decimal(32,6) NOT NULL ,
    clear_entry_type int NOT NULL ,
    busi_flag int NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_merge_clear_1 on tb_clfocl_merge_clear (exch_no,order_date,order_no);
create index idx_tb_clfocl_merge_clear_2 on tb_clfocl_merge_clear (strike_date,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_clfocl_merge_clear_3 on tb_clfocl_merge_clear (strike_date,futu_acco_no,contrc_code_no);

-- 创建数据表：历史_清算外盘期货_清算_合并清算表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_merge_clear_his;
CREATE TABLE tb_clfocl_merge_clear_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    split_rece_margin decimal(32,6) NOT NULL ,
    split_strike_qty decimal(18,2) NOT NULL ,
    split_strike_amt decimal(32,6) NOT NULL ,
    split_report_fee decimal(32,6) NOT NULL ,
    split_cancel_fee decimal(32,6) NOT NULL ,
    split_deli_fee decimal(32,6) NOT NULL ,
    split_other_fee decimal(32,6) NOT NULL ,
    split_brkage_commis decimal(32,6) NOT NULL ,
    split_other_commis decimal(32,6) NOT NULL ,
    split_out_strike_qty decimal(18,2) NOT NULL ,
    split_out_strike_amt decimal(32,6) NOT NULL ,
    split_out_report_fee decimal(32,6) NOT NULL ,
    split_out_cancel_fee decimal(32,6) NOT NULL ,
    split_out_deli_fee decimal(32,6) NOT NULL ,
    split_out_other_fee decimal(32,6) NOT NULL ,
    split_out_brkage_commis decimal(32,6) NOT NULL ,
    split_out_other_commis decimal(32,6) NOT NULL ,
    clear_entry_type int NOT NULL ,
    busi_flag int NOT NULL ,
    deal_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_clfocl_merge_clear_his_1 on tb_clfocl_merge_clear_his (exch_no,order_date,order_no);
create index idx_tb_clfocl_merge_clear_his_2 on tb_clfocl_merge_clear_his (strike_date,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_clfocl_merge_clear_his_3 on tb_clfocl_merge_clear_his (strike_date,futu_acco_no,contrc_code_no);

-- 创建数据表：清算外盘期货_清算_待入账记录表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_pre_entry;
CREATE TABLE tb_clfocl_pre_entry (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    entry_status varchar(2) NOT NULL ,
    undo_status varchar(2) NOT NULL ,
    entry_money_jour_no bigint NOT NULL ,
    entry_posi_jour_no bigint NOT NULL ,
    deli_jour_no bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfocl_pre_entry_1 on tb_clfocl_pre_entry (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);
create index idx_tb_clfocl_pre_entry_2 on tb_clfocl_pre_entry (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：历史_清算外盘期货_清算_待入账记录表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_pre_entry_his;
CREATE TABLE tb_clfocl_pre_entry_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    entry_status varchar(2) NOT NULL ,
    undo_status varchar(2) NOT NULL ,
    entry_money_jour_no bigint NOT NULL ,
    entry_posi_jour_no bigint NOT NULL ,
    deli_jour_no bigint NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfocl_pre_entry_his_1 on tb_clfocl_pre_entry_his (pass_no,out_acco,exch_no,strike_date,strike_no,order_dir);
create index idx_tb_clfocl_pre_entry_his_2 on tb_clfocl_pre_entry_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：清算外盘期货_清算_入账异常表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_entry_error;
CREATE TABLE tb_clfocl_entry_error (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    undo_error_no int NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfocl_entry_error_1 on tb_clfocl_entry_error (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：历史_清算外盘期货_清算_入账异常表
use db_clfofu_his;
DROP TABLE IF EXISTS tb_clfocl_entry_error_his;
CREATE TABLE tb_clfocl_entry_error_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    strike_date int NOT NULL ,
    strike_time int NOT NULL ,
    strike_no varchar(32) NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_no int NOT NULL ,
    order_dir int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    pre_settle_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    strike_num int NOT NULL ,
    pre_entry_qty decimal(18,2) NOT NULL ,
    pre_entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    comb_type int NOT NULL ,
    comb_name varchar(64) NOT NULL ,
    long_hold_margin decimal(32,6) NOT NULL ,
    short_hold_margin decimal(32,6) NOT NULL ,
    sett_capt_margin decimal(32,6) NOT NULL ,
    sett_close_pandl decimal(32,6) NOT NULL ,
    sett_marked_pandl decimal(32,6) NOT NULL ,
    sett_close_pandl_today decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    busi_flag int NOT NULL ,
    undo_error_no int NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfocl_entry_error_his_1 on tb_clfocl_entry_error_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);

-- 创建数据表：清算外盘期货_清算_统计表
use db_clfofu;
DROP TABLE IF EXISTS tb_clfocl_total;
CREATE TABLE tb_clfocl_total (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    invest_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_type int NOT NULL ,
    busi_flag int NOT NULL ,
    order_dir int NOT NULL ,
    strike_num int NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    sett_price decimal(16,9) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(32,6) NOT NULL ,
    entry_qty decimal(18,2) NOT NULL ,
    entry_amt decimal(32,6) NOT NULL ,
    rece_margin decimal(32,6) NOT NULL ,
    all_fee decimal(32,6) NOT NULL ,
    report_fee decimal(32,6) NOT NULL ,
    wtdraw_fee decimal(32,6) NOT NULL ,
    deli_fee decimal(32,6) NOT NULL ,
    other_fee decimal(32,6) NOT NULL ,
    trade_commis decimal(32,6) NOT NULL ,
    other_commis decimal(32,6) NOT NULL ,
    out_all_fee decimal(32,6) NOT NULL ,
    out_report_fee decimal(32,6) NOT NULL ,
    out_cancel_fee decimal(32,6) NOT NULL ,
    out_deli_fee decimal(32,6) NOT NULL ,
    out_other_fee decimal(32,6) NOT NULL ,
    out_brkage_commis decimal(32,6) NOT NULL ,
    out_other_commis decimal(32,6) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_clfocl_total_1 on tb_clfocl_total (init_date,busi_flag,co_no,pd_no,exch_group_no,asset_acco_no);
commit;
