#创建公共_期货费用_费用编号表初始化记录！
use db_pub;
truncate db_pub.tb_fee_futu_fee_no;
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,510100,51,1,0,"买入保证金");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,510101,51,1,1,"开仓买入保证金");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,510200,51,2,0,"卖出保证金");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,510201,51,2,1,"开仓卖出保证金");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520100,52,1,0,"买入手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520101,52,1,1,"开仓买入手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520102,52,1,2,"平仓买入手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520103,52,1,3,"平今仓买入手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520200,52,2,0,"卖出手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520201,52,2,1,"开仓卖出手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520202,52,2,2,"平仓卖出手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,520203,52,2,3,"平今仓卖出手续费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,530000,53,0,0,"期货申报费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,540000,54,0,0,"期货撤单费");
insert into db_pub.tb_fee_futu_fee_no(create_date,create_time,update_date,update_time,update_times,fee_no,futu_fee_type,order_dir,contrc_dir,remark_info) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,550000,55,0,0,"期货交割费");
commit;
