-- /**************************************************************************************/
-- 创建数据库【交易期货】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdfutu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdfutu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：交易期货_交易_订单表
use db_tdfutu;
DROP TABLE IF EXISTS tb_tdfutd_order;
CREATE TABLE tb_tdfutd_order (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    asset_type int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    trade_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    strike_commis decimal(18,4) NOT NULL ,
    strike_other_commis decimal(18,4) NOT NULL ,
    report_fee decimal(18,4) NOT NULL ,
    wtdraw_fee decimal(18,4) NOT NULL ,
    strike_all_fee decimal(18,4) NOT NULL ,
    rece_margin decimal(18,4) NOT NULL ,
    trade_occur_amt decimal(18,4) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    margin_ratio decimal(18,12) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    sett_flag int NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_order_1 on tb_tdfutd_order (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdfutd_order_2 on tb_tdfutd_order (order_date,order_batch_no);
create index idx_tb_tdfutd_order_3 on tb_tdfutd_order (order_date,order_status);
create index idx_tb_tdfutd_order_4 on tb_tdfutd_order (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdfutd_order_5 on tb_tdfutd_order (futu_acco_no,contrc_code_no);

-- 创建数据表：历史_交易期货_交易_订单表
use db_tdfutu_his;
DROP TABLE IF EXISTS tb_tdfutd_order_his;
CREATE TABLE tb_tdfutd_order_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    asset_type int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    external_no bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    order_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_price decimal(16,9) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    trade_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    strike_commis decimal(18,4) NOT NULL ,
    strike_other_commis decimal(18,4) NOT NULL ,
    report_fee decimal(18,4) NOT NULL ,
    wtdraw_fee decimal(18,4) NOT NULL ,
    strike_all_fee decimal(18,4) NOT NULL ,
    rece_margin decimal(18,4) NOT NULL ,
    trade_occur_amt decimal(18,4) NOT NULL ,
    comb_code varchar(6) NOT NULL ,
    margin_ratio decimal(18,12) NOT NULL ,
    rsp_info varchar(255) NOT NULL ,
    compli_trig_id bigint NOT NULL ,
    sett_flag int NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_order_his_1 on tb_tdfutd_order_his (pass_no,out_acco,exch_no,report_no,report_date);
create index idx_tb_tdfutd_order_his_2 on tb_tdfutd_order_his (order_date,order_batch_no);
create index idx_tb_tdfutd_order_his_3 on tb_tdfutd_order_his (order_date,order_status);
create index idx_tb_tdfutd_order_his_4 on tb_tdfutd_order_his (init_date,co_no,pd_no,exch_group_no);
create index idx_tb_tdfutd_order_his_5 on tb_tdfutd_order_his (futu_acco_no,contrc_code_no);

-- 创建数据表：交易期货_交易_撤单表
use db_tdfutu;
DROP TABLE IF EXISTS tb_tdfutd_wtdraw;
CREATE TABLE tb_tdfutd_wtdraw (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    external_no bigint NOT NULL ,
    wtdraw_batch_no int NOT NULL ,
    wtdraw_date int NOT NULL ,
    wtdraw_time int NOT NULL ,
    order_date int NOT NULL ,
    order_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    wtdraw_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    wtdraw_remark varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_wtdraw_1 on tb_tdfutd_wtdraw (order_id);
create index idx_tb_tdfutd_wtdraw_2 on tb_tdfutd_wtdraw (report_date,report_no);
create index idx_tb_tdfutd_wtdraw_3 on tb_tdfutd_wtdraw (wtdraw_status);
create index idx_tb_tdfutd_wtdraw_4 on tb_tdfutd_wtdraw (wtdraw_date);

-- 创建数据表：历史_交易期货_交易_撤单表
use db_tdfutu_his;
DROP TABLE IF EXISTS tb_tdfutd_wtdraw_his;
CREATE TABLE tb_tdfutd_wtdraw_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    futu_acco_no int NOT NULL ,
    futu_acco varchar(16) NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    external_no bigint NOT NULL ,
    wtdraw_batch_no int NOT NULL ,
    wtdraw_date int NOT NULL ,
    wtdraw_time int NOT NULL ,
    order_date int NOT NULL ,
    order_id bigint NOT NULL ,
    report_date int NOT NULL ,
    report_time int NOT NULL ,
    report_no varchar(32) NOT NULL ,
    wtdraw_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    wtdraw_remark varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_wtdraw_his_1 on tb_tdfutd_wtdraw_his (order_id);
create index idx_tb_tdfutd_wtdraw_his_2 on tb_tdfutd_wtdraw_his (report_date,report_no);
create index idx_tb_tdfutd_wtdraw_his_3 on tb_tdfutd_wtdraw_his (wtdraw_status);
create index idx_tb_tdfutd_wtdraw_his_4 on tb_tdfutd_wtdraw_his (wtdraw_date);

-- 创建数据表：交易期货_交易_订单汇总表
use db_tdfutu;
DROP TABLE IF EXISTS tb_tdfutd_sumorder;
CREATE TABLE tb_tdfutd_sumorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    asset_type int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_sum_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    waste_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    trade_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    strike_commis decimal(18,4) NOT NULL ,
    strike_other_commis decimal(18,4) NOT NULL ,
    report_fee decimal(18,4) NOT NULL ,
    wtdraw_fee decimal(18,4) NOT NULL ,
    strike_all_fee decimal(18,4) NOT NULL ,
    rece_margin decimal(18,4) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdfutd_sumorder_1 on tb_tdfutd_sumorder (order_date,co_no,order_batch_no);
create index idx_tb_tdfutd_sumorder_2 on tb_tdfutd_sumorder (opor_no,order_oper_way);

-- 创建数据表：历史_交易期货_交易_订单汇总表
use db_tdfutu_his;
DROP TABLE IF EXISTS tb_tdfutd_sumorder_his;
CREATE TABLE tb_tdfutd_sumorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    asset_type int NOT NULL ,
    contrc_type int NOT NULL ,
    contrc_unit int NOT NULL ,
    external_no bigint NOT NULL ,
    order_batch_no int NOT NULL ,
    order_date int NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_sum_status varchar(2) NOT NULL ,
    wtdraw_qty decimal(18,2) NOT NULL ,
    waste_qty decimal(18,2) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    strike_aver_price decimal(16,9) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    trade_fee decimal(18,4) NOT NULL ,
    trade_commis decimal(18,4) NOT NULL ,
    other_commis decimal(18,4) NOT NULL ,
    strike_commis decimal(18,4) NOT NULL ,
    strike_other_commis decimal(18,4) NOT NULL ,
    report_fee decimal(18,4) NOT NULL ,
    wtdraw_fee decimal(18,4) NOT NULL ,
    strike_all_fee decimal(18,4) NOT NULL ,
    rece_margin decimal(18,4) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdfutd_sumorder_his_1 on tb_tdfutd_sumorder_his (order_date,co_no,order_batch_no);
create index idx_tb_tdfutd_sumorder_his_2 on tb_tdfutd_sumorder_his (opor_no,order_oper_way);

-- 创建数据表：交易期货_交易_改单表
use db_tdfutu;
DROP TABLE IF EXISTS tb_tdfutd_modifyorder;
CREATE TABLE tb_tdfutd_modifyorder (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    contrc_type int NOT NULL ,
    asset_type int NOT NULL ,
    modi_order_date int NOT NULL ,
    modi_order_time int NOT NULL ,
    modi_batch_no int NOT NULL ,
    order_id bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    price_type int NOT NULL ,
    modi_order_price decimal(16,9) NOT NULL ,
    modi_order_qty decimal(18,2) NOT NULL ,
    modi_order_status varchar(2) NOT NULL ,
    modi_price_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    new_order_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_modifyorder_1 on tb_tdfutd_modifyorder (modi_order_date,order_id);
create index idx_tb_tdfutd_modifyorder_2 on tb_tdfutd_modifyorder (init_date,co_no,pd_no,exch_group_no);

-- 创建数据表：历史_交易期货_交易_改单表
use db_tdfutu_his;
DROP TABLE IF EXISTS tb_tdfutd_modifyorder_his;
CREATE TABLE tb_tdfutd_modifyorder_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    exch_no int NOT NULL ,
    contrc_code_no int NOT NULL ,
    contrc_code varchar(6) NOT NULL ,
    contrc_type int NOT NULL ,
    asset_type int NOT NULL ,
    modi_order_date int NOT NULL ,
    modi_order_time int NOT NULL ,
    modi_batch_no int NOT NULL ,
    order_id bigint NOT NULL ,
    comm_id bigint NOT NULL ,
    order_price decimal(16,9) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    order_dir int NOT NULL ,
    contrc_dir int NOT NULL ,
    hedge_type int NOT NULL ,
    order_date int NOT NULL ,
    order_time int NOT NULL ,
    price_type int NOT NULL ,
    modi_order_price decimal(16,9) NOT NULL ,
    modi_order_qty decimal(18,2) NOT NULL ,
    modi_order_status varchar(2) NOT NULL ,
    modi_price_type int NOT NULL ,
    crncy_type varchar(3) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    new_order_id bigint NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    order_oper_way varchar(2) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdfutd_modifyorder_his_1 on tb_tdfutd_modifyorder_his (modi_order_date,order_id);
create index idx_tb_tdfutd_modifyorder_his_2 on tb_tdfutd_modifyorder_his (init_date,co_no,pd_no,exch_group_no);
commit;
