-- /**************************************************************************************/
-- 创建数据库【交易证券】及其之上的数据表
-- /**************************************************************************************/
CREATE DATABASE IF NOT EXISTS db_logic DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
CREATE DATABASE IF NOT EXISTS db_tdsecu_his DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

-- 创建数据表：交易证券_指令_指令表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_command;
CREATE TABLE tb_tdseap_command (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    comm_frozen_amt decimal(18,4) NOT NULL ,
    comm_frozen_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    capit_reback_days int NOT NULL ,
    posi_reback_days int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_status varchar(2) NOT NULL ,
    comm_appr_oper_no int NOT NULL ,
    comm_appr_oper int NOT NULL ,
    comm_appr_remark varchar(255) NOT NULL ,
    basket_id bigint NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_comple_flag int NOT NULL ,
    strategy_order_qty decimal(18,2) NOT NULL ,
    strategy_capt_qty decimal(18,2) NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    target_stock_code varchar(6) NOT NULL ,
    target_stock_code_no int NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    workflow_type int NOT NULL ,
    contra_no varchar(32) NOT NULL ,
    asset_acco_type int NOT NULL ,
    exist_debt_flag int NOT NULL ,
    disp_opor int NOT NULL ,
    disp_status int NOT NULL ,
    read_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_1 on tb_tdseap_command (comm_batch_no);
create index idx_tb_tdseap_command_2 on tb_tdseap_command (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_3 on tb_tdseap_command (comm_date,comm_end_date);
create index idx_tb_tdseap_command_4 on tb_tdseap_command (exter_comm_flag,comm_comple_flag);
create index idx_tb_tdseap_command_5 on tb_tdseap_command (stock_acco_no,stock_code_no);
create index idx_tb_tdseap_command_6 on tb_tdseap_command (combo_code);
create index idx_tb_tdseap_command_7 on tb_tdseap_command (update_date,update_time);

-- 创建数据表：历史_交易证券_指令_指令表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_command_his;
CREATE TABLE tb_tdseap_command_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    comm_frozen_amt decimal(18,4) NOT NULL ,
    comm_frozen_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    capit_reback_days int NOT NULL ,
    posi_reback_days int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_status varchar(2) NOT NULL ,
    comm_appr_oper_no int NOT NULL ,
    comm_appr_oper int NOT NULL ,
    comm_appr_remark varchar(255) NOT NULL ,
    basket_id bigint NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_comple_flag int NOT NULL ,
    strategy_order_qty decimal(18,2) NOT NULL ,
    strategy_capt_qty decimal(18,2) NOT NULL ,
    combo_code varchar(32) NOT NULL ,
    target_stock_code varchar(6) NOT NULL ,
    target_stock_code_no int NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    workflow_type int NOT NULL ,
    contra_no varchar(32) NOT NULL ,
    asset_acco_type int NOT NULL ,
    exist_debt_flag int NOT NULL ,
    disp_opor int NOT NULL ,
    disp_status int NOT NULL ,
    read_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_his_1 on tb_tdseap_command_his (comm_batch_no);
create index idx_tb_tdseap_command_his_2 on tb_tdseap_command_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_his_3 on tb_tdseap_command_his (comm_date,comm_end_date);
create index idx_tb_tdseap_command_his_4 on tb_tdseap_command_his (exter_comm_flag,comm_comple_flag);
create index idx_tb_tdseap_command_his_5 on tb_tdseap_command_his (stock_acco_no,stock_code_no);
create index idx_tb_tdseap_command_his_6 on tb_tdseap_command_his (combo_code);
create index idx_tb_tdseap_command_his_7 on tb_tdseap_command_his (update_date,update_time);

-- 创建数据表：交易证券_指令_指令流水表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_command_jour;
CREATE TABLE tb_tdseap_command_jour (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    jour_occur_field varchar(2048) NOT NULL ,
    jour_occur_info varchar(2048) NOT NULL ,
    jour_after_occur_info varchar(2048) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_jour_1 on tb_tdseap_command_jour (init_date,comm_id);
create index idx_tb_tdseap_command_jour_2 on tb_tdseap_command_jour (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_jour_3 on tb_tdseap_command_jour (init_date,opor_co_no,opor_no);
create index idx_tb_tdseap_command_jour_4 on tb_tdseap_command_jour (exter_comm_flag);

-- 创建数据表：历史_交易证券_指令_指令流水表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_command_jour_his;
CREATE TABLE tb_tdseap_command_jour_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    jour_occur_field varchar(2048) NOT NULL ,
    jour_occur_info varchar(2048) NOT NULL ,
    jour_after_occur_info varchar(2048) NOT NULL ,
    remark_info varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_jour_his_1 on tb_tdseap_command_jour_his (init_date,comm_id);
create index idx_tb_tdseap_command_jour_his_2 on tb_tdseap_command_jour_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_jour_his_3 on tb_tdseap_command_jour_his (init_date,opor_co_no,opor_no);
create index idx_tb_tdseap_command_jour_his_4 on tb_tdseap_command_jour_his (exter_comm_flag);

-- 创建数据表：交易证券_指令_指令分发表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_command_dispense;
CREATE TABLE tb_tdseap_command_dispense (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_opor int NOT NULL ,
    disp_date int NOT NULL ,
    disp_time int NOT NULL ,
    before_comm_executor int NOT NULL ,
    comm_executor int NOT NULL ,
    is_withdraw int NOT NULL ,
    disp_flag int NOT NULL ,
    disp_remark varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_dispense_1 on tb_tdseap_command_dispense (comm_date,comm_id);
create index idx_tb_tdseap_command_dispense_2 on tb_tdseap_command_dispense (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_dispense_3 on tb_tdseap_command_dispense (exter_comm_flag);

-- 创建数据表：历史_交易证券_指令_指令分发表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_command_dispense_his;
CREATE TABLE tb_tdseap_command_dispense_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_opor int NOT NULL ,
    disp_date int NOT NULL ,
    disp_time int NOT NULL ,
    before_comm_executor int NOT NULL ,
    comm_executor int NOT NULL ,
    is_withdraw int NOT NULL ,
    disp_flag int NOT NULL ,
    disp_remark varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_dispense_his_1 on tb_tdseap_command_dispense_his (comm_date,comm_id);
create index idx_tb_tdseap_command_dispense_his_2 on tb_tdseap_command_dispense_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_dispense_his_3 on tb_tdseap_command_dispense_his (exter_comm_flag);

-- 创建数据表：交易证券_指令_指令审批表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_command_approve;
CREATE TABLE tb_tdseap_command_approve (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_oper_no int NOT NULL ,
    comm_appr_oper int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_opor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_appr_status varchar(2) NOT NULL ,
    comm_appr_remark varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_approve_1 on tb_tdseap_command_approve (comm_appr_date,comm_appr_oper);
create index idx_tb_tdseap_command_approve_2 on tb_tdseap_command_approve (comm_date,comm_id);
create index idx_tb_tdseap_command_approve_3 on tb_tdseap_command_approve (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_approve_4 on tb_tdseap_command_approve (exter_comm_flag);

-- 创建数据表：历史_交易证券_指令_指令审批表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_command_approve_his;
CREATE TABLE tb_tdseap_command_approve_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_oper_no int NOT NULL ,
    comm_appr_oper int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_opor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_appr_status varchar(2) NOT NULL ,
    comm_appr_remark varchar(255) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_approve_his_1 on tb_tdseap_command_approve_his (comm_appr_date,comm_appr_oper);
create index idx_tb_tdseap_command_approve_his_2 on tb_tdseap_command_approve_his (comm_date,comm_id);
create index idx_tb_tdseap_command_approve_his_3 on tb_tdseap_command_approve_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_approve_his_4 on tb_tdseap_command_approve_his (exter_comm_flag);

-- 创建数据表：交易证券_指令_指令汇总表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_sumcommand;
CREATE TABLE tb_tdseap_sumcommand (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    comm_await_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_sum_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    max_comm_comple_date int NOT NULL ,
    max_comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_qty decimal(18,2) NOT NULL ,
    comm_sum_approve_status varchar(2) NOT NULL ,
    basket_id bigint NOT NULL ,
    buy_order_qty decimal(18,2) NOT NULL ,
    sell_order_qty decimal(18,2) NOT NULL ,
    buy_comm_qty decimal(18,2) NOT NULL ,
    sell_comm_qty decimal(18,2) NOT NULL ,
    buy_strike_qty decimal(18,2) NOT NULL ,
    sell_strike_qty decimal(18,2) NOT NULL ,
    buy_strike_amt decimal(18,4) NOT NULL ,
    sell_strike_amt decimal(18,4) NOT NULL ,
    buy_comm_amt decimal(18,4) NOT NULL ,
    sell_comm_amt decimal(18,4) NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    read_flag int NOT NULL ,
    acco_concat_info varchar(4096) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdseap_sumcommand_1 on tb_tdseap_sumcommand (comm_date,co_no,comm_batch_no,comm_executor);
create index idx_tb_tdseap_sumcommand_2 on tb_tdseap_sumcommand (opor_no,comm_oper_way);
create index idx_tb_tdseap_sumcommand_3 on tb_tdseap_sumcommand (exter_comm_flag);

-- 创建数据表：历史_交易证券_指令_指令汇总表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_sumcommand_his;
CREATE TABLE tb_tdseap_sumcommand_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    pass_no int NOT NULL ,
    out_acco varchar(32) NOT NULL ,
    exch_crncy_type varchar(3) NOT NULL ,
    exch_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_code varchar(6) NOT NULL ,
    target_code_no int NOT NULL ,
    trade_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_time int NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_limit_price decimal(16,9) NOT NULL ,
    limit_actual_price decimal(16,9) NOT NULL ,
    comm_qty decimal(18,2) NOT NULL ,
    comm_amt decimal(18,4) NOT NULL ,
    order_qty decimal(18,2) NOT NULL ,
    comm_cancel_qty decimal(18,2) NOT NULL ,
    comm_await_cancel_qty decimal(18,2) NOT NULL ,
    strike_amt decimal(18,4) NOT NULL ,
    strike_qty decimal(18,2) NOT NULL ,
    net_price_flag int NOT NULL ,
    par_value decimal(16,9) NOT NULL ,
    impawn_ratio decimal(18,12) NOT NULL ,
    intrst_days int NOT NULL ,
    bond_accr_intrst decimal(18,12) NOT NULL ,
    bond_rate_type int NOT NULL ,
    strike_status varchar(2) NOT NULL ,
    comm_sum_status varchar(2) NOT NULL ,
    comm_begin_date int NOT NULL ,
    comm_end_date int NOT NULL ,
    comm_begin_time int NOT NULL ,
    comm_end_time int NOT NULL ,
    comm_comple_date int NOT NULL ,
    comm_comple_time int NOT NULL ,
    max_comm_comple_date int NOT NULL ,
    max_comm_comple_time int NOT NULL ,
    comm_appr_date int NOT NULL ,
    comm_appr_time int NOT NULL ,
    comm_appr_qty decimal(18,2) NOT NULL ,
    comm_sum_approve_status varchar(2) NOT NULL ,
    basket_id bigint NOT NULL ,
    buy_order_qty decimal(18,2) NOT NULL ,
    sell_order_qty decimal(18,2) NOT NULL ,
    buy_comm_qty decimal(18,2) NOT NULL ,
    sell_comm_qty decimal(18,2) NOT NULL ,
    buy_strike_qty decimal(18,2) NOT NULL ,
    sell_strike_qty decimal(18,2) NOT NULL ,
    buy_strike_amt decimal(18,4) NOT NULL ,
    sell_strike_amt decimal(18,4) NOT NULL ,
    buy_comm_amt decimal(18,4) NOT NULL ,
    sell_comm_amt decimal(18,4) NOT NULL ,
    comm_oper_way varchar(2) NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_remark_info varchar(1024) NOT NULL ,
    read_flag int NOT NULL ,
    acco_concat_info varchar(4096) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create unique index idx_tb_tdseap_sumcommand_his_1 on tb_tdseap_sumcommand_his (comm_date,co_no,comm_batch_no,comm_executor);
create index idx_tb_tdseap_sumcommand_his_2 on tb_tdseap_sumcommand_his (opor_no,comm_oper_way);
create index idx_tb_tdseap_sumcommand_his_3 on tb_tdseap_sumcommand_his (exter_comm_flag);

-- 创建数据表：交易证券_指令_指令转发审批表
use db_tdsecu;
DROP TABLE IF EXISTS tb_tdseap_command_dispense_approve;
CREATE TABLE tb_tdseap_command_dispense_approve (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    disp_flag int NOT NULL ,
    disp_remark varchar(255) NOT NULL ,
    before_comm_executor int NOT NULL ,
    is_withdraw int NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_dispense_appr_status varchar(2) NOT NULL ,
    comm_dispense_appr_opor int NOT NULL ,
    comm_dispense_appr_date int NOT NULL ,
    comm_dispense_appr_time int NOT NULL ,
    comm_dispense_appr_remark varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_dispense_approve_1 on tb_tdseap_command_dispense_approve (comm_dispense_appr_date,comm_dispense_appr_opor);
create index idx_tb_tdseap_command_dispense_approve_2 on tb_tdseap_command_dispense_approve (comm_date,comm_id);
create index idx_tb_tdseap_command_dispense_approve_3 on tb_tdseap_command_dispense_approve (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_dispense_approve_4 on tb_tdseap_command_dispense_approve (exter_comm_flag);

-- 创建数据表：历史_交易证券_指令_指令转发审批表
use db_tdsecu_his;
DROP TABLE IF EXISTS tb_tdseap_command_dispense_approve_his;
CREATE TABLE tb_tdseap_command_dispense_approve_his (
    row_id bigint NOT NULL AUTO_INCREMENT,
    create_date int NOT NULL ,
    create_time int NOT NULL ,
    update_date int NOT NULL ,
    update_time int NOT NULL ,
    update_times int NOT NULL ,
    opor_co_no int NOT NULL ,
    opor_no int NOT NULL ,
    oper_mac varchar(32) NOT NULL ,
    oper_ip_addr varchar(32) NOT NULL ,
    oper_info varchar(1024) NOT NULL ,
    oper_way varchar(2) NOT NULL ,
    oper_func_code varchar(16) NOT NULL ,
    init_date int NOT NULL ,
    co_no int NOT NULL ,
    pd_no int NOT NULL ,
    exch_group_no int NOT NULL ,
    asset_acco_no int NOT NULL ,
    exch_no int NOT NULL ,
    stock_acco_no int NOT NULL ,
    stock_code_no int NOT NULL ,
    stock_type int NOT NULL ,
    asset_type int NOT NULL ,
    comm_date int NOT NULL ,
    comm_id bigint NOT NULL ,
    comm_batch_no int NOT NULL ,
    comm_dir int NOT NULL ,
    comm_status varchar(2) NOT NULL ,
    comm_opor int NOT NULL ,
    comm_executor int NOT NULL ,
    disp_flag int NOT NULL ,
    disp_remark varchar(255) NOT NULL ,
    before_comm_executor int NOT NULL ,
    is_withdraw int NOT NULL ,
    exter_comm_flag int NOT NULL ,
    comm_dispense_appr_status varchar(2) NOT NULL ,
    comm_dispense_appr_opor int NOT NULL ,
    comm_dispense_appr_date int NOT NULL ,
    comm_dispense_appr_time int NOT NULL ,
    comm_dispense_appr_remark varchar(255) NOT NULL ,
    PRIMARY KEY (row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
create index idx_tb_tdseap_command_dispense_approve_his_1 on tb_tdseap_command_dispense_approve_his (comm_dispense_appr_date,comm_dispense_appr_opor);
create index idx_tb_tdseap_command_dispense_approve_his_2 on tb_tdseap_command_dispense_approve_his (comm_date,comm_id);
create index idx_tb_tdseap_command_dispense_approve_his_3 on tb_tdseap_command_dispense_approve_his (init_date,co_no,pd_no,exch_group_no,asset_acco_no);
create index idx_tb_tdseap_command_dispense_approve_his_4 on tb_tdseap_command_dispense_approve_his (exter_comm_flag);
commit;
