#创建交易证券_交易_交易时间配置表初始化记录！
use db_tdsecu;
truncate db_tdsecu.tb_tdsetd_trdtimeconfig;
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,1,1,91500,113100);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,1,2,125900,150500);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,2,1,91500,113100);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,2,2,125900,150500);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,3,1,90000,120100);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,3,2,125900,161000);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,4,1,90000,120100);
insert into db_tdsecu.tb_tdsetd_trdtimeconfig(create_date,create_time,update_date,update_time,update_times,exch_no,trd_time_interval,begin_time,end_time) values(date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),date_format(curdate(),'%Y%m%d'),date_format(curtime(),'%H%i%s'),1,4,2,125900,161000);
commit;
